### ISSUE TITLE
Deebot N10 map support

### ISSUE THREAD

**Issue by hawkpd** [DeebotUniverse/docs#239] opened 2023-07-13 17:23 UTC
I have got this working for my Deebot N10 but it's unable to display a map from the device.  Is this an easy fix?  I have a working N10 if you need any info grabbed from it.
Thanks
Paul

**Comment by rahulpdev** [comment] 2023-10-13 07:13
> I have got this working for my Deebot N10 but it's unable to display a map from the device. Is this an easy fix? I have a working N10 if you need any info grabbed from it. Thanks Paul

I also have the T10 Plus, are you able to clean zones in your house via Home Assistant? I haven't figured out how to do that!

**Comment by edenhaus** [comment] 2023-12-13 11:18
Duplicate of https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/268

**Closed by edenhaus** 2023-12-13 11:18 UTC
